version: '3.8'

services:
  oracle-ebs-surrogate:
    image: machshop/oracle-ebs-surrogate:latest
    container_name: oracle-ebs-surrogate-prod
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: production
      PORT: 3002
      DB_PATH: /app/data/oracle-ebs.db
      LOG_LEVEL: info
    volumes:
      - oracle-ebs-data:/app/data
    networks:
      - oracle-ebs-network
    restart: always
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3002/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    # Security options
    security_opt:
      - no-new-privileges:true
    read_only_root_filesystem: true
    tmpfs:
      - /tmp
      - /app/data

volumes:
  oracle-ebs-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/oracle-ebs

networks:
  oracle-ebs-network:
    driver: bridge
